services:
  postgres:
    image: postgres:15
    container_name: springboot_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATASOURCE_DBNAME}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_HOST: postgres
      DATASOURCE_PORT: ${DATASOURCE_PORT}
      DATASOURCE_DBNAME: ${DATASOURCE_DBNAME}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
    depends_on:
      - postgres

volumes:
  pgdata:
